/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/9ab1eb3bb97f4e4a9305c0aae2d280a6
title: Saturn (planet)
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Saturn({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/saturn_planet/scene.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes["Saturn_Material_#50_0"].geometry}
              material={materials.Material_50}
            />
          </group>
          <group
            name="Saturn_Clouds"
            rotation={[-Math.PI / 2, 0, -0.02]}
            scale={101}
          >
            <mesh
              geometry={nodes["Saturn_Clouds_Material_#62_0"].geometry}
              material={materials.Material_62}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes["Saturn_Rings_Material_#63_0"].geometry}
              material={materials.Material_63}
            />
          </group>
          <group
            position={[-988.32, 0, -1127.88]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes["Sphere_Mimas_Material_#64_0"].geometry}
              material={nodes["Sphere_Mimas_Material_#64_0"].material}
            />
          </group>
          <group
            position={[1784.73, 0, 239.89]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes["Sphere_Enceladus_Material_#64_0"].geometry}
              material={nodes["Sphere_Enceladus_Material_#64_0"].material}
            />
          </group>
          <group
            position={[-3011.73, 0, -1085.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes["Sphere_Dione_Material_#64_0"].geometry}
              material={nodes["Sphere_Dione_Material_#64_0"].material}
            />
          </group>
          <group
            position={[-2969.68, 0, -3375.37]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes["Sphere_Rhea_Material_#64_0"].geometry}
              material={nodes["Sphere_Rhea_Material_#64_0"].material}
            />
          </group>
          <group
            position={[396.37, 0, 2165.97]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes["Sphere_Tethys_Material_#64_0"].geometry}
              material={nodes["Sphere_Tethys_Material_#64_0"].material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/saturn_planet/scene.gltf");
